### ISSUE TITLE
Would you please introduce more details about this hackintosh?

### ISSUE THREAD

**Issue by DWPang** [tinhkma/Hackintosh-Dell-Precision-5530-OC-boot#1]
Hello!

I am attempting to run Catalina (10.15.6) on DELL Precision 5530, thanks for creating this repo.
Would you please introduce more details about this hackintosh, for example: 
1) CPU and memory configuration about your DELL Precision 5530
2) What is working and not working on your hackintosh, for example: stable or not, power management, suspend/sleep, wireless, type-c port, HDMI to external display and so on.

Thank you very much!

**Comment by tinhkma** [comment]
used for all versions
